# Generated by Django 2.1.1 on 2018-09-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='made_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Customer'),
            preserve_default=False,
        ),
    ]
